language: objective-c
osx_image: xcode7.3
xcode_workspace: NXDrawKit.xcworkspace
xcode_scheme: NXDrawKit-Example
xcode_sdk: iphonesimulator9.3

before_install:
  - cd Example
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet

script:
  - xcodebuild build test -project NXDrawKit.xcodeproj -scheme NXDrawKit-Example | xcpretty
